#!/bin/sh

# from fedora workstation netinstall
# standard X desktop

if [ `id --user` -ne 0 ]; then
    echo "the script must be run as root."
    exit 1
fi

# bug on F24 workstation netinstall
#LANG=en_US.UTF-8 dnf install -y glibc-langpack-fr

dnf clean all -y

dnf install -y firefox mupdf
dnf install -y xorg-x11-drv-libinput
dnf install -y py3status dconf gnome-keyring
dnf install -y terminus-fonts fontawesome-fonts breeze-icon-theme
dnf install -y vim git man-pages-fr
dnf install -y redshift xbacklight pass
dnf install -y preload powertop

# devel
dnf install -y gcc rpm-build rpmdevtools
# devel compton
dnf install -y libX11-devel libXcomposite-devel libXdamage-devel libXrender-devel
dnf install -y libXext-devel libXrandr-devel libXinerama-devel
dnf install -y libconfig-devel dbus-devel mesa-libGL-devel pcre-devel

# remove
dnf remove -y awesome dwm openbox-* ratpoison xmonad-*

exit 0
