#!/bin/sh

# you must be root
if [ `id -u` -ne 0 ]; then
    echo "this script must be run as root."
    exit 1
fi

# enable openh264 repo
dnf config-manager --set-enabled fedora-cisco-openh264

# install mozilla plugin
dnf install -y mozilla-openh264

# install gstreamer plugin
#dnf install gstreamer1-plugin-openh264

exit 0
