#!/bin/sh

# you must be root
if [ `id -u` -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

# copy config file
cp 50-lightdm-auth.conf /etc/lightdm/lightdm.conf.d
# edit gtk greeter
cat lightdm-gtk-greeter.conf >> /etc/lightdm/lightdm-gtk-greeter.conf
