#!/bin/sh

ID=ideapad-S300

## you must be root

if [ `id -u` -ne 0 ]; then
    echo "You must be root !"
    exit 1
fi

## copy configfile

cp -i -v 00-$ID.rules /etc/udev/rules.d/
cp -i -v 10-$ID.conf /etc/sysctl.d/
cp -i -v $ID.conf /etc/modprobe.d/
cp -i -v rc.local /etc/rc.d/


## tweak


## disable services

sh unwanted-services.sh
