#!/bin/sh

ID=ideapad-S300

## you must be root

if [ `id -u` -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

## copy configfile
cp -i -v 00-$ID.rules /etc/udev/rules.d/
cp -i -v 10-$ID.conf /etc/sysctl.d/
cp -i -v $ID.conf /etc/modprobe.d/
cp -i -v rc.local /etc/rc.d/
chmod 755 /etc/rc.d/rc.local
systemctl enable rc-local

# tweak fstab
sh fstab.sh

# disable services
sh unwanted-services.sh

echo "Restart the system for apply change."
