syntax on

"set t_Co=256
"set t_Co=88
set nocompatible
"set background=dark
set ttyfast
set ruler
set nowrap

" show line number
set nu
"hi LineNr ctermfg=darkgray
hi LineNr ctermbg=black ctermfg=cyan

" status bar
set wildmenu
set showcmd
set laststatus=2
hi StatusLine cterm=reverse

" tabs
set tabstop=4
set shiftwidth=1
set expandtab

" show hidden characters
set backspace=eol,start,indent
" set listchars=nbsp:¤,trail:¤,tab:^^
set listchars=nbsp:·,trail:·,tab:\ \ 
set list
hi NonText ctermfg=darkgray
hi SpecialKey ctermfg=darkgray

" indent
filetype plugin indent on
set autoindent
set smartindent

" encodage
set encoding=utf8
set ffs=unix,dos,mac

" no backup file
set nobackup
set nowb
set noswapfile

" search
set ignorecase
set smartcase
set incsearch
set hlsearch
